### ISSUE TITLE
[Feature Request] Target multiple variant options within compound variants

### ISSUE THREAD

**Issue by kyh** [sannajammeh/tw-classed#113]
**Is your feature request related to a problem? Please describe.**
Currently migrating some styles over from `cva` -> `tw-classed` and running into some API compatibility issues. This could also for people using https://github.com/shadcn/ui 

**Describe the solution you'd like**
Same feature as https://github.com/joe-bell/cva/pull/76

```
const button = classed("button", {
  variants: {
    intent: {
      primary: "button--primary",
      secondary: "button--secondary",
      warning: "button--warning",
    },
    disabled: {
      true: "button--disabled",
      false: "button--enabled",
    },
  },
  compoundVariants: [
    {
      // ✨ apply to `secondary` and `warning` intents ✨
      intent: ["secondary", "warning"],
      disabled: true,
      class: "text-black",
    },
  ],
});
```

**Comment by sannajammeh** [comment]
Good issue! 

I am a bit swamped trying to release an app this week, should be an easy fix though so hoping I can land it on Sunday

**Comment by sannajammeh** [comment]
Just landed! Took a bit longer than expected to clear my schedule.
