### ISSUE TITLE
Export cx utility

### ISSUE THREAD

**Issue by maltesa** [sannajammeh/tw-classed#116]
**Is your feature request related to a problem? Please describe.**
Sometimes it feels like overkill to use the `classed` function just to add an `active` etc toggle to a component. For those cases I would love to use the `clsx`, but I do not want to add it as a dependency, as I already have tw-classed.

**Describe the solution you'd like**
I've seen that tw-classed uses a utility called `cx` internally. It would be great if the bundle would export it.

**Describe alternatives you've considered**
Adding `clsx` to my dependencies

**Comment by sannajammeh** [comment]
Definitely, good issue! Will get on that asap
