### ISSUE TITLE
DataAttributes don't seem to be merged/created when composing classes

### ISSUE THREAD

**Issue by d-henn** [sannajammeh/tw-classed#123]
**Describe the bug**

Just want to make sure I'm not missing something when leveraging class composition. I'm trying to compose a `button` class component and merge into my specific styled buttons. I'm using the `dataAttributes: ['...']` feature as part of the base class creation, but when I go to use this class within my other `button` classes  it doesn't seem to add the markup for the `data-xyz`.

**To Reproduce**

1. Create two components, one as a base component that uses the `dataAttributes`

```ts
const BaseButton = classed.button('font-medium', {
  variants: {
    color: {
      green: 'bg-green',
      blue: 'bg-blue',
    },
  },
  dataAttributes: ['color'],
});
```
2. Create another component that will be composed with the first original base component
```ts
const SizeButton = classed.button(BaseButton, {
  variants: {
    size: {
      small: 'px-2 py-1',
      medium: 'px-3 py-2',
    },
  },
});
```

**Expected behavior**

Below is what I would expect to see as the merged output on the `<button />`

```html
// usage
<SizeButton color="blue" size="medium">Button</SizeButton>

// result
<button class="font-medium bg-blue px-3 py-2" data-color="blue">Button</button> <-- data-color exists 😁
```

**Screenshots**

What I actually get is
```html
// usage
<SizeButton color="blue" size="medium">Button</SizeButton>

// result
<button class="font-medium bg-blue px-3 py-2">Button</button> <-- data-color missing ☹️
```

**Environment? (please complete the following information):**
 - OS: [e.g. iOS]: `Mac OS Ventura 13.6`
 - Browser [e.g. chrome, safari]: `Firefox`
 - Node.js Version: `v18.8.0`
 - Version [e.g. 22] `1.5.2`

**Additional context**

Just using one standard component seems to work appropriately

```ts
const BaseButton = classed.button('font-medium', {
  variants: {
    color: {
      green: 'bg-green',
      blue: 'bg-blue',
    },
  },
  dataAttributes: ['color'],
});
```

```html
// usage
<BaseButton color="blue">Button</BaseButton>

// result
<button class="font-medium bg-blue" data-color="blue">Button</button> <-- data-color exists 😁
```

----

Seeing if this is the expected behavior, or if I'm using it in an unintended/incorrect manner?

Thanks for this incredible library!

**Comment by sannajammeh** [comment]
Looking into this. Definitely should be the case as its simply wrapping the underlying component when used as the first argument

**Comment by sannajammeh** [comment]
Hi, was looking into this and spotted the reason this wasn't working. 

This is indeed correct behavior as you're not extending the previous component, you're overriding it.

```tsx
const SizeButton = classed.button(BaseButton, {
  variants: {
    size: {
      small: 'px-2 py-1',
      medium: 'px-3 py-2',
    },
  },
});
```

What this does is rendering an html button element, skipping the BaseButton and pulls the variants off the BaseButton to use merged with the variants from your object. BaseButton is no longer the underlying component, its not rendered at all actually.

This would be the correct usage, notice we have omitted `.button` from the classed method, this tells classed to use BaseButton as the underlying component:
```tsx
const SizeButton = classed(BaseButton, {
  variants: {
    size: {
      small: 'px-2 py-1',
      medium: 'px-3 py-2',
    },
  },
});
```

**Comment by sannajammeh** [comment]
Anyhow, I noticed a bug in that case too. The fix is actually making both cases work :D

PR will be submitted very soon
