### ISSUE TITLE
Issues with TypeScript exactOptionalPropertyTypes

### ISSUE THREAD

**Issue by BorisZubchenko** [sannajammeh/tw-classed#130]
**Describe the bug**
The same as mentioned [here](https://github.com/nextui-org/tailwind-variants/issues/115) and [here](https://github.com/chakra-ui/panda/issues/1688): `with 'exactOptionalPropertyTypes: true'. Consider adding undefined to the types of the target's properties.`

**To Reproduce**
```tsx
const Example = classed('div', '', {
  variants: {
    size: {
      lg: '',
      sm: '',
    },
  },
})

Example({
  size: undefined // << here
})
```

**Expected behavior**
I should be able to pass undefined (implicitly and explicitly).

**Screenshots**
![image](https://github.com/sannajammeh/tw-classed/assets/31354262/c87cad4d-f714-41c8-82f7-2ef210614389)

**Environment? (please complete the following information):**
 - OS: N/A
 - Browser N/A
 - Node.js N/A
 - Version 1.6.1

**Comment by sannajammeh** [comment]
Thanks for brining this to my attention! Seems a lot of libs have forgotten about this type, even `stitches`. Fixing in same release as #131
