### ISSUE TITLE
Attach a variantMap to a component

### ISSUE THREAD

**Issue by BorisZubchenko** [sannajammeh/tw-classed#131]
**Is your feature request related to a problem? Please describe.**
When using Storybook, it's often convenient to have all the variants that can be applied to the component.

For example, for this component:
```tsx
const Icon = classed(
  'svg',
  '...',
  {
    defaultVariants: {
      size: 'md',
    },
    variants: {
      size: {
        'sm': 'h-4 w-4',
        'md': 'h-5 w-5',
        'lg': 'h-6 w-6',
      },
      variant: {
        'primary': '...',
        'secondary': '...'
      }
    },
  },
)
```
I want `Icon.variantMap` to return:
```tsx
{
  size: ['sm', 'md', 'lg'],
  variant: ['primary', 'secondary']
}
```
So that I can automate the creation of Storybook's [argTypes](https://storybook.js.org/docs/api/arg-types):
```tsx
const meta = {
  argTypes: {
    ...variantArgTypes(Icon.variantMap),
  },
  component: Icon,
} satisfies Meta<typeof Icon>

export default meta
```

**Describe the solution you'd like**
[This one](https://panda-css.com/docs/concepts/recipes#methods-and-properties)

**Describe alternatives you've considered**
1. Duplicate:
```tsx
...variantArgTypes({
  size: ['xs', 'sm', 'md', 'lg', 'xl', '2xl'],
}),
```
2. Extract:
```tsx
const variants = variants: {
  size: {
    'sm': 'h-4 w-4',
    'md': 'h-5 w-5',
    'lg': 'h-6 w-6',
  },
  variant: {
    'primary': '...',
    'secondary': '...'
  }
},

const Icon = classed(
  'svg',
  '...',
  {
    defaultVariants: {
      size: 'md',
    },
    variants
  },
)
```

**Comment by sannajammeh** [comment]
We Are actually already doing this! We just dont have a utility that extracts them yet, that is a small fix, should be ready by end of today :)

**Comment by sannajammeh** [comment]
This is the test case for the new functionality. Just to confirm is this correct?  

```ts
const button = classed("button", {
      base: "bg-blue-500",
      variants: {
        size: {
          sm: "text-sm",
          md: "text-md",
          lg: "text-lg",
        },
        color: {
          red: "text-red-500",
          blue: "text-blue-500",
          green: "text-green-500",
        },
      },
      defaultVariants: {
        size: "lg",
        color: "red",
      },
      compoundVariants: [
        {
          size: "lg",
          color: ["red", "blue"],
          className: "MATCH",
        },
      ],
    });

    const variants = getVariants(button);

    expect(variants).toEqual({
      className: "button bg-blue-500",
      variants: {
        size: {
          sm: "text-sm",
          md: "text-md",
          lg: "text-lg",
        },
        color: {
          red: "text-red-500",
          blue: "text-blue-500",
          green: "text-green-500",
        },
      },
      defaultVariants: {
        size: "lg",
        color: "red",
      },
      compoundVariants: [
        {
          size: "lg",
          color: ["red", "blue"],
          className: "MATCH",
        },
      ],
    });
```

**Comment by BorisZubchenko** [comment]
Thank you for a quick response!

Your solution includes Tailwind classes. However, they're unnecessary for providing argTypes.

Here's the edited API I propose. I would treat it like "run-time types for variants":

```tsx
const Button = classed("button", {
  base: "bg-blue-500",
  variants: {
    size: {
      sm: "text-sm",
      md: "text-md",
      lg: "text-lg",
    },
    color: {
      red: "text-red-500",
      blue: "text-blue-500",
      green: "text-green-500",
    },
  },
  defaultVariants: {
    size: "lg",
    color: "red",
  },
  compoundVariants: [
    {
      size: "lg",
      color: ["red", "blue"],
      className: "MATCH",
    },
  ],
});
  
expect(Button.variantMap).toEqual({
  size: ['sm', 'md', 'lg'],
  color: ['red', 'green', 'blue']
});

**Comment by sannajammeh** [comment]
Thanks for the suggestion. I think I prefer the functionality in my current code. Here is the reasoning.

1. Internally a unique `Symbol` is used to map the variants using `Reflect`
2. Providing a variantMap by default will degrade performance. Panda can afford to do so because they run everything at compile time, our mapping of variants is at runtime. This will greatly increase the time complexity of the classed() function.

As soon as @tw-classed@1.7.0 is out, we have a way to extract the variants at runtime. I think it should be up to the user to transform these as they see fit. 

Here is a utility to transform them to your desired shape: 
```ts
type OutputObject<T extends object> = {
  [Key in keyof T]: string[];
};
function getVariantMap<T extends Record<string, any>>(
  input: T
): OutputObject<T> {
  const output: Partial<OutputObject<T>> = {};

  for (const key in input) {
    if (input.hasOwnProperty(key)) {
      const values = Object.keys(input[key as keyof T]);
      output[key] = values;
    }
  }

  return output as OutputObject<T>;
}

const input = {
  size: {
    sm: "text-sm",
    md: "text-md",
    lg: "text-lg",
  },
  color: {
    red: "text-red-500",
    blue: "text-blue-500",
    green: "text-green-500",
  },
};

const output = getVariantMap(input);

// Res
{
  size: [ "sm", "md", "lg" ],
  color: [ "red", "blue", "green" ],
}
```

I do see some use in adding this as a separate function though. Perhaps exported from `@tw-classed/react/utils`

Then it can be called directly on a component with 

```tsx
const variantMap = getVariantMap(Button)
const variantKeys = getVariantKeys(Button)
```

**Comment by BorisZubchenko** [comment]
Regarding performance, `classed` function is a HoC, thus, executes once, not every re-render:

However, your solution with `getVariantMap(Button)` looks better in terms of separation of concerns. So I agree it's more convenient.

**Comment by sannajammeh** [comment]
v1.7 is releasing now with `getVariantConfig` exported. v1.8 will include the proposed `getVariantMap` and `getVariantKeys` utilities
