### ISSUE TITLE
Make defaultProps a function

### ISSUE THREAD

**Issue by BorisZubchenko** [sannajammeh/tw-classed#142]
**Is your feature request related to a problem? Please describe.**
Sometimes it's important to wrap component's `children` with another component:
```tsx
function Component({children, ...props}) {
  return <div {...props}>
    <Wrapper>{children}</Wrapper> // not just {children}
  </div>
}
```
For example, look at the [Plate.js HeadingElement](https://platejs.org/docs/components/heading-element) (see Installation -> Manual).

Classed has a `defaultProps` property:
```tsx
const ButtonWithText = classed('button', {
  defaultProps: {
    children: 'Submit'
  }
})
```
However, we can't create a classed component that wraps the `children`:
```tsx
const Button = classed('button', {
  defaultProps: {
    children: <Wrapper>{children}</Wrapper> // we can't, we don't have an access to the children
  }
})
```

**Describe the solution you'd like**
What if `defaultProps` were be a function instead?
```tsx
const Button = classed('button', {
  defaultProps: (props) => ({
    children: <Wrapper>{props.children}</Wrapper>
  })
})
```

**Describe alternatives you've considered**
Just use plain React

**Additional context**
I tried to implement [something similar](https://gist.github.com/BorisZubchenko/950709f092cc6440afbabfe2d9276312#file-withprops-tsx-L39), so the Plate HeadingElement above could look like this:
```tsx
function basicElement<ElementTypeT extends ElementType>(Element: ElementTypeT) {
  return withProps(PlateElement, ({ children }) => ({
    asChild: true,
    children: <Element>{children}</Element>,
  }))
}

const H1 = basicElement('h1')
const H2 = basicElement('h2')
const H3 = basicElement('h3')
```
I'm not sure about performance though.

**Comment by sannajammeh** [comment]
I think `deriveClassed` is the function you're looking for. This retains all variant functionality and provides an API similar to forwardRef around a class components while keeping the types compatible and the `as` prop functional.

https://tw-classed.vercel.app/docs/derived-components

**Comment by BorisZubchenko** [comment]
In this exact case, I think the `deriveClassed` is no different from the `forwardRef`. And we have to provide two generic arguments, which is extremely annoying. I guess in most cases this can be done in a more declarative way.
