### ISSUE TITLE
How do we type variant props in tw-classed/core?

### ISSUE THREAD

**Issue by afreidz** [sannajammeh/tw-classed#48]
On the doc site, there is a link to typescript usage within the core module.  However the docs show typings being imported from react rather than core.  I tried to leverage the same types/generics in core and was unable to find the `VariantProps` generic.

![Screenshot 2022-12-01 at 4 12 34 PM](https://user-images.githubusercontent.com/1158247/205170179-14d17ddb-bab2-4d38-b156-45133b11f732.png)

how might i generate a type for variants for a core `tw-classed` instance?

**Comment by sannajammeh** [comment]
Hello.

Released in 1.2.4. Its available once you update. 

Also on the Core Docs now.

**Comment by afreidz** [comment]
awesome! thanks
