### ISSUE TITLE
Remove Literal types "true"/"false" from type of Boolean Variants

### ISSUE THREAD

**Issue by maltesa** [sannajammeh/tw-classed#49]
**Is your feature request related to a problem? Please describe.**
When using Boolean-Variants the resulting type looks something like this:
```tsx
const BasicButton = classed('button', { variants: { loading: { true: 'animate-pulse' } } })
// => { loading: boolean | "true" | undefined }

const ButtonContent = classed('div', { variants: { loading: { false: 'invisible' } } })
// => { loading: boolean | "false" | undefined }

const Button = ({ loading, children, ...props}: React.ComponentProps<typeof BasicButton>) => (
<BasicButton loading={loading} {...props}>
  <ButtonContent loading={loading}>{children}</ButtonContent>
  {/* => Type 'boolean | "true" | undefined' is not assignable to type 'boolean | "false" | undefined'. */}
</BasicButton>
)
```

**Describe the solution you'd like**
Do not include Literal types "true" and "false" in the type of Boolean-Variants.

**Describe alternatives you've considered**
```
  loading = loading === 'true' || loading
```

**Comment by sannajammeh** [comment]
Widening the type even more might be a better solution. 
I cross checked with Stitches.js, they have the same issue.

Widening it to boolean | "true" | "false" | undefined will fix the issue without breaking anyone using string matching. On it.

**Comment by maltesa** [comment]
Yes, right. That would solve my issue 👍
