### ISSUE TITLE
Support for intellisense suggestions

### ISSUE THREAD

**Issue by getlaurekt** [sannajammeh/tw-classed#75]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Support for class suggestions inside classed

**Describe alternatives you've considered**
Only typing the object in ts, but its not the most productive

**Additional context**
The suggestion would be displayed in strings in classed object, same goes for variants etc.
![image](https://user-images.githubusercontent.com/58201840/209698277-3ab09a97-60de-4039-9ced-dd879318437a.png)

Is that possible? I have used similiar package that was supporting prettier and intellisense aswell if i remember correctly, it was working differently tho([twined package](https://github.com/lowfront/twined-components))

**Comment by sannajammeh** [comment]
Hello,

Yes its detailed in the Docs.

https://tw-classed.vercel.app/docs/vscode-setup

**Comment by getlaurekt** [comment]
> 

Oh jeez, idk how i missed that... i totally forgot about it when first time i was checking classed, sorry for making the issue, now its working.
