### ISSUE TITLE
How would I extend subcomponents to ClassedComponentType

### ISSUE THREAD

**Issue by kyh** [sannajammeh/tw-classed#77]
<img width="938" alt="Screen Shot 2023-01-01 at 6 03 47 PM" src="https://user-images.githubusercontent.com/4271679/210190741-387ac898-5bf4-411e-a1f3-7d3e7595a2cc.png">

TS Error:
```
Property 'Item' does not exist on type 'ClassedComponentType<"ul", {}, {}>'
```

**Comment by sannajammeh** [comment]
You must map the type manually. Typescript does not support the above unless its a raw function using pure inferrence.
```tsx
const List = classed(...);

type ListComponentType = typeof List & {
Item: typeof ListItem
}

(List as ListComponentType).Item = ListItem;

export default List as ListComponentType
```
