### ISSUE TITLE
required variant

### ISSUE THREAD

**Issue by Newbie012** [sannajammeh/tw-classed#79]
**Is your feature request related to a problem? Please describe.**

Right now, (AFAIK) there's no way we can create a required variant

**Describe the solution you'd like**

allow to make a required variant

**Describe alternatives you've considered**

wrap inside another component

**Additional context**

**Comment by sannajammeh** [comment]
Hello :)

This is discussed in #44 so I'm going to close this for now. Would appreciate your input on my suggestions there as I want this to be an opt-in feature.
