### ISSUE TITLE
Composing components with different default `as` props

### ISSUE THREAD

**Issue by kyh** [sannajammeh/tw-classed#80]
**Describe the bug**
I'm having trouble composing a component with a different `as` property

**To Reproduce**
Component 1:
```
import { classed, DerivedComponentType } from "@tw-classed/react";
import { forwardRef } from "react";

const BaseText = classed("span", {
  base: "t-1",
  variants: {
    variant: {
      label1: "l-1"
    }
  }
});

type TextProps = React.ComponentProps<typeof BaseText>;

export const Text = forwardRef<HTMLSpanElement, TextProps>(function Text(
  { children, ...props },
  ref
) {
  return (
    <BaseText {...props} ref={ref}>
      Text component: {children}
    </BaseText>
  );
}) as DerivedComponentType<typeof BaseText, TextProps>;
```

Component 2:
```
const BaseLabel = classed(Text, {
  base: "t-2"
});

type LabelProps = React.ComponentProps<typeof BaseLabel>;

export const Label = forwardRef<HTMLLabelElement, LabelProps>(function Label(
  { ...props },
  ref
) {
  return <BaseLabel ref={ref} as="label" variant="label1" {...props} />;
}) as DerivedComponentType<typeof BaseLabel, LabelProps>;
```

"Component 2" throws a ts error when it has the `as` property on `BaseLabel`

Repro: https://codesandbox.io/embed/goofy-fast-jspjve?fontsize=14&hidenavigation=1&theme=dark

Is there a different way for me to do this sort of composition?

**Comment by sannajammeh** [comment]
Thank you for this issue!

I find it very weird that TS complains because it is producing the intellisense somehow.

![image](https://user-images.githubusercontent.com/50969683/210699832-3a495b4e-0e21-4076-8317-6480e85d7504.png)

If I set the `as` to an `a` tag then I get the href property. So this means that Typescript was able to following the `as` prop all the way down to the `Polymorphic overload` yet still complains. 

I will investigate further

**Comment by sannajammeh** [comment]
![image](https://user-images.githubusercontent.com/50969683/210700270-9b4c53ec-88eb-4381-8964-85c0844a54cf.png)

Found the issue! It's the same React issue I faced and the reason why DerivedComponentType was created. React flattens the type of the `as` prop from `keyof JSX.IntrinsicElements | ClassedComponentType` to `ClassedComponentType`. Same with `ref` prop.

### Solution
Omit from props `as` & `ref`
```tsx
const Label = forwardRef<HTMLLabelElement, Omit<LabelProps, "as" | "ref">>(
    function Label({ ...props }, ref) {
      return <BaseLabel ref={ref} as="label" {...props} />;
    }
  ) as DerivedComponentType<typeof BaseLabel, LabelProps>;
```

I will investigate further to see if I can modify the internals to omit these two by default. Maybe write and export a custom ComponentProps that doesn't flatten the types.

**Comment by sannajammeh** [comment]
Pushed a new canary release. Contains the new deriveClassed API:

https://tw-classed-canary.vercel.app/docs/derived-components

install `@tw-classed/react@canary`
