### ISSUE TITLE
Extending Radix components leads to displayName: TwComponent([object Object])

### ISSUE THREAD

**Issue by maltesa** [sannajammeh/tw-classed#91]
**Describe the bug**
When using classed on radix components, the `displayName` of the resulting component is: `TwComponent([object Object])`.

**To Reproduce**
[https://stackblitz.com/edit/nextjs-8fjahy?file=pages/index.js](https://stackblitz.com/edit/nextjs-8fjahy?file=pages/index.js)

**Expected behavior**
From this code 
https://github.com/sannajammeh/tw-classed/blob/e02cb3b862abcf5cef69e01c14d01697cbffc854/packages/react/src/classed.tsx#L71

I assumed the displayName of the RadixComponent would have been used.

**Comment by sannajammeh** [comment]
Fixes in `1.4.1`!

**Comment by maltesa** [comment]
Thank you ♥
