### ISSUE TITLE
Does it work with nativewind or support react-native?

### ISSUE THREAD

**Issue by ammarfaris** [sannajammeh/tw-classed#98]
Hi there, nice work on tw-classed! Just wondering if it work with nativewind  https://github.com/marklawlor/nativewind (to make it work with react-native) or will you support react-native in the future?

Thanks!

**Comment by sannajammeh** [comment]
V3 of Nativewind has support and this library wont be needed then, but it has some Expo EAS issues.

We run Nativewind + tw-classed in production without any issues. Going to be moving this to discussions :)

Example:

```tsx
import { styled } from "nativewind";
import { classed } from "@tw-classed/react";

const StyledTouchableOpacity = styled(TouchableOpacity);

export const ButtonBase = classed(StyledTouchableOpacity, {
  variants: {
    color: {
      primary: "bg-chew-primary",
      secondary: "bg-chew-secondary",
      slate: "bg-slate-300 text-slate-800",
    },
    size: {
      sm: "px-2 py-2",
      md: "px-4 py-3",
      lg: "px-6 py-4",
    },
    rounded: {
      sm: "rounded-sm",
      md: "rounded-md",
      lg: "rounded-lg",
      xl: "rounded-xl",
      "2xl": "rounded-2xl",
      full: "rounded-full",
    },
  },

  defaultVariants: {
    color: "primary",
    size: "md",
    rounded: "2xl",
  },
});
```

**Comment by sannajammeh** [comment]
Since nativewind will have support for this in V3 natively, I will add some docs for doing it manually with tw-classed for now. Leaving issue open until docs are complete

**Comment by ammarfaris** [comment]
thanks for your time and explanation ; and for the (future) docs, appreciate it!

**Comment by sannajammeh** [comment]
Docs are now up in the `Guides` section

**Comment by PrajTS** [comment]
Hey, this does not seem to work with v4. No styles seems to get applied. 

Eg: 
export const XStack = classes(View, 'flex-row')

seem to have no affect. It still renders a default View with flex-col

**Comment by sannajammeh** [comment]
> Hey @sannajammeh , this does not seem to work with v4. No styles seems to get applied. 
> 
> 
> 
> Eg: 
> 
> export const XStack = classes(View, 'flex-row')
> 
> 
> 
> seem to have no affect. It still renders a default View with flex-col

Could you provide a Repro?

**Comment by PrajTS** [comment]
Repro - https://github.com/PrajTS/nativewind-tw-classed

**Comment by visualcookie** [comment]
I'm facing the same issue now too, but other than the `View`, it does not work for me on React Native's text component. I've created the following `classed`:
``` tsx
export const Text = classed(RNText, {
  variants: {
    hierarchy: {
      [Hierarchy.Primary]: 'text-white',
      [Hierarchy.Secondary]: 'text-primary',
      [Hierarchy.Link]: 'text-petrol',
    },
  },
});
```

But the library does not render any of these classes. From what I've seen in the React Native React Devtools is, that there is not `CssInterop` being set for the `Text` `classed`, while for my container, which is a `Pressable` there is, hence why the background switching per hierarchy for my buttons work, but the switching to a different text color doesn't. I also have another problem: the `disabled` state is also not working, even tho it is defined as per the docs.

From the looks at it, your library may still need an update for Nativewind v4.

**Comment by sannajammeh** [comment]
> I'm facing the same issue now too, but other than the `View`, it does not work for me on React Native's text component. I've created the following `classed`:
> 
> ```tsx
> export const Text = classed(RNText, {
>   variants: {
>     hierarchy: {
>       [Hierarchy.Primary]: 'text-white',
>       [Hierarchy.Secondary]: 'text-primary',
>       [Hierarchy.Link]: 'text-petrol',
>     },
>   },
> });
> ```
> 
> But the library does not render any of these classes. From what I've seen in the React Native React Devtools is, that there is not `CssInterop` being set for the `Text` `classed`, while for my container, which is a `Pressable` there is, hence why the background switching per hierarchy for my buttons work, but the switching to a different text color doesn't. I also have another problem: the `disabled` state is also not working, even tho it is defined as per the docs.
> 
> From the looks at it, your library may still need an update for Nativewind v4.

I'm on it! Quite busy with project releases with the coming weeks, but we should have this done very soon :)

**Comment by PrajTS** [comment]
Hey, any update on this?
